<?php

declare(strict_types = 1);

namespace Shinya\PhpRadser\Rfc2866\Attributes;

use Override;
use Shinya\PhpRadser\Attributes\StringAttribute;

/**
 * unique identifier for this session, matching its Start and Stop accounting records; typically
 * generated by the NAS.
 *
 * @example '00000001'
 */
class AcctSessionId extends StringAttribute
{
	#[Override]
	public static function identifier(): string
	{
		return 'Acct-Session-Id';
	}

	#[Override]
	public static function type(): int
	{
		return 44;
	}
}
